spring:
  application:
    name: Store
  profiles:
    active: dev

#server:
#  servlet:
#    context-path: /fake-store


springdoc:
  swagger-ui:
    path: /
    defaultModelsExpandDepth: -1 #This ensures: ✅ Schemas are hidden,
