spring:
  application:
    name: FakeStore
  profiles:
    active: dev

#server:
#  servlet:
#    context-path: /fake-store


springdoc:
  swagger-ui:
    path: /api-docs
    defaultModelsExpandDepth: -1 #This ensures: ✅ Schemas are hidden,
