spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root123@cluster0.sicxk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
      database: storedb
      username: root
      password: 123
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
