spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root123@cluster0.sicxk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
      database: fake-store-db
      username: root
      password: 123
server:
  port: 8080